spring.application.name=Lobby-Service
spring.config.import=optional:file:./.env.properties
# Redis

spring.cache.type=redis

spring.data.redis.host=${REDIS_HOST:}
spring.data.redis.port=${REDIS_PORT:6380}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL:true}

# MongoDB Atlas
spring.data.mongodb.uri=${MONGO_URI:}

# RabbitMQ - CloudAMQP
spring.rabbitmq.host=${RABBITMQ_HOST:yak.lmq.cloudamqp.com}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:mkqpekbi}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:ZbiyBjraVzdd4oCfwxYeOlsBwhFB2NDx}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:mkqpekbi}

app.base-url=http://localhost:8080