spring.application.name=Lobby-Service
spring.config.import=optional:file:./.env.properties
# Redis

spring.cache.type=redis

spring.data.redis.host=${REDIS_HOST:}
spring.data.redis.port=${REDIS_PORT:6380}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${REDIS_SSL:true}

# MongoDB Atlas
spring.data.mongodb.uri=${MONGO_URI:}


# RabbitMQ
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest