spring.application.name=Lobby-Service
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis
spring.data.mongodb.uri=mongodb+srv://rangeljuanfe687_db_user:M00n141604@cluster0.txg68t8.mongodb.net/